name: action5
description: This is action5

runs:
  using: "composite"

  steps:
    - name: View context attributes
      uses: actions/github-script@v9
      with:
        script: |
          const { default: doStuff } = await import('${{ github.action_path }}/script.ts');
          const result = await doStuff({github, context});
          console.log(result);
